name = "Dynamic Technology"
author = "Uncraftbar"
version = "0.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c18ac587adc88559619ff458791a5ec1e130e88fc1c9bd61615b82b387b080d0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.213"

[export]
[export.curseforge]
project-id = 1230297
